version: "3"
services:
  wireguard:
    #image: ffmd/wireguard:latest
    build: wireguard/
    env_file: .env
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  babeld:
    #image: ffmd/babeld:latest
    build: babeld/
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.accept_redirects=0
      - net.ipv4.conf.all.rp_filter=0
    restart: unless-stopped
    env_file: .env

  l3roamd:
    #image: ffmd/l3roamd:latest
    build: l3roamd/
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    env_file: .env

  mmfd:
    #image: ffmd/mmfd:latest
    build: mmfd/
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    env_file: .env
